# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:16
    container_name: expense_tracker_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=expense_tracker # This ensures the DB is created
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - expense_tracker_network

networks:
  expense_tracker_network:
    driver: bridge

volumes:
  postgres_data:
